ALTER TYPE "accountType" ADD VALUE 'doctor';--> statement-breakpoint
ALTER TYPE "speciality" ADD VALUE 'endocrinologist';--> statement-breakpoint
ALTER TYPE "speciality" ADD VALUE 'gastroenterologist';--> statement-breakpoint
ALTER TYPE "speciality" ADD VALUE 'hematologist';--> statement-breakpoint
ALTER TYPE "speciality" ADD VALUE 'infectiousDiseaseSpecialist';--> statement-breakpoint
ALTER TYPE "speciality" ADD VALUE 'nephrologist';--> statement-breakpoint
ALTER TYPE "speciality" ADD VALUE 'oncologist';--> statement-breakpoint
ALTER TYPE "speciality" ADD VALUE 'osteopath';--> statement-breakpoint
ALTER TYPE "speciality" ADD VALUE 'otolaryngologist';--> statement-breakpoint
ALTER TYPE "speciality" ADD VALUE 'physiatrist';--> statement-breakpoint
ALTER TYPE "speciality" ADD VALUE 'plasticSurgeon';--> statement-breakpoint
ALTER TYPE "speciality" ADD VALUE 'podiatrist';--> statement-breakpoint
ALTER TYPE "speciality" ADD VALUE 'pulmonologist';--> statement-breakpoint
ALTER TYPE "speciality" ADD VALUE 'radiologist';--> statement-breakpoint
ALTER TYPE "speciality" ADD VALUE 'rheumatologist';--> statement-breakpoint
ALTER TYPE "speciality" ADD VALUE 'allergist';--> statement-breakpoint
ALTER TYPE "speciality" ADD VALUE 'anesthesiologist';--> statement-breakpoint
ALTER TYPE "speciality" ADD VALUE 'cardiacElectrophysiologist';--> statement-breakpoint
ALTER TYPE "speciality" ADD VALUE 'criticalCareMedicineSpecialist';--> statement-breakpoint
ALTER TYPE "speciality" ADD VALUE 'emergencyMedicineSpecialist';--> statement-breakpoint
ALTER TYPE "speciality" ADD VALUE 'familyMedicinePhysician';--> statement-breakpoint
ALTER TYPE "speciality" ADD VALUE 'hospitalist';--> statement-breakpoint
ALTER TYPE "speciality" ADD VALUE 'internist';--> statement-breakpoint
ALTER TYPE "speciality" ADD VALUE 'medicalGeneticist';--> statement-breakpoint
ALTER TYPE "speciality" ADD VALUE 'obstetrician';--> statement-breakpoint
ALTER TYPE "speciality" ADD VALUE 'occupationalMedicineSpecialist';--> statement-breakpoint
ALTER TYPE "speciality" ADD VALUE 'painManagementSpecialist';--> statement-breakpoint
ALTER TYPE "speciality" ADD VALUE 'pathologist';--> statement-breakpoint
ALTER TYPE "speciality" ADD VALUE 'physicalMedicineAndRehabilitationSpecialist';--> statement-breakpoint
ALTER TYPE "speciality" ADD VALUE 'preventiveMedicineSpecialist';--> statement-breakpoint
ALTER TYPE "speciality" ADD VALUE 'sleepMedicineSpecialist';--> statement-breakpoint
ALTER TYPE "speciality" ADD VALUE 'sportsMedicineSpecialist';--> statement-breakpoint
ALTER TYPE "speciality" ADD VALUE 'surgeon';--> statement-breakpoint
ALTER TYPE "speciality" ADD VALUE 'vascularSurgeon';--> statement-breakpoint
ALTER TYPE "speciality" ADD VALUE 'veterinarian';--> statement-breakpoint
ALTER TYPE "speciality" ADD VALUE 'virologist';--> statement-breakpoint
ALTER TYPE "speciality" ADD VALUE 'other';